import { useEffect, useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import useAuth from "../../features/auth/hooks/useAuth";
import styles from "./MyShopDashboard.module.css";

const API_URL = import.meta.env.PROD 
  ? "" 
  : (import.meta.env.VITE_API_URL || "http://localhost:5000").replace(/\/\$/, "");

// Cloudinary unsigned upload URL (set in your environment variables)
const CLOUDINARY_UPLOAD_URL = import.meta.env.VITE_CLOUDINARY_UPLOAD_URL;

export default function MyShopDashboard() {
  const navigate = useNavigate();
  const { auth } = useAuth();
  const currentUserId = auth?.currentUser?.uid;

  // Existing States...
  const [activeTab, setActiveTab] = useState("inventory");
  const [allProducts, setAllProducts] = useState([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [walletBalance, setWalletBalance] = useState("0.00");
  const [totalRevenue, setTotalRevenue] = useState(0);
  const [totalSold, setTotalSold] = useState(0);
  const [sidebarOrderCount, setSidebarOrderCount] = useState(0);
  const [isModalOpen, setIsModalOpen] = useState(false);
  
  // New States for Form Inputs
  const [productName, setProductName] = useState('');
  const [productPrice, setProductPrice] = useState('');
  const [productQuantity, setProductQuantity] = useState('');
  const [productImage, setProductImage] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState({});
  
  // Existing useEffects...
  useEffect(() => {
    if (!currentUserId) return;
    const runMasterDashboardSync = async () => {
      try {
        setIsLoading(true);
        const invResponse = await fetch(`${API_URL}/api/products?shopId=${currentUserId}`);
        if (invResponse.ok) {
          const invData = await invResponse.json();
          setAllProducts(invData);
        }
        await loadSalesStats();
        await syncDashboardWalletBalance();
      } catch (err) {
        console.error("Master dashboard sync cycle interrupted:", err);
      } finally {
        setIsLoading(false);
      }
    };
    runMasterDashboardSync();
  }, [currentUserId]);

  const syncDashboardWalletBalance = async () => {
    try {
      const response = await fetch(`${API_URL}/api/wallets/balance`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          "x-user-id": currentUserId,
        },
      });
      if (!response.ok) throw new Error("Could not map balance profile.");
      const data = await response.json();
      if (data.wallet) {
        const formatted = parseFloat(data.wallet.balance || 0).toLocaleString(
          "en-KE",
          {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          }
        );
        setWalletBalance(formatted);
      }
    } catch (err) {
      console.error("Balance asset verification skipped:", err);
    }
  };

  const loadSalesStats = async () => {
    try {
      const response = await fetch(`${API_URL}/api/products/sales-summary`);
      if (response.ok) {
        const data = await response.json();
        setTotalRevenue(data.revenue || 0);
        setTotalSold(data.count || 0);
        setSidebarOrderCount(data.count || 0);
      }
    } catch (err) {
      console.log("Sales analytics matrices not yet generated by backend nodes.");
    }
  };

  // Upload Image to Cloudinary
  const uploadImageToCloudinary = async (file) => {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('upload_preset', 'YOUR_UPLOAD_PRESET'); // set your upload preset

    const response = await fetch(CLOUDINARY_UPLOAD_URL, {
      method: 'POST',
      body: formData,
    });
    const data = await response.json();
    if (response.ok) {
      return data.secure_url;
    } else {
      throw new Error(data.error.message || 'Upload failed');
    }
  };

  // Handle Form Submission
  const handleSubmit = async () => {
    // Validate
    const newErrors = {};
    if (!productName) newErrors.name = 'Product name is required.';
    if (!productPrice || isNaN(productPrice)) newErrors.price = 'Valid price required.';
    if (!productQuantity || isNaN(productQuantity)) newErrors.quantity = 'Valid quantity required.';
    if (!productImage) newErrors.image = 'Product image is required.';
    setErrors(newErrors);
    if (Object.keys(newErrors).length > 0) return;

    setIsSubmitting(true);
    try {
      // Upload image
      const imageUrl = await uploadImageToCloudinary(productImage);

      // Send data to backend
      const payload = {
        name: productName,
        price: parseFloat(productPrice),
        quantity: parseInt(productQuantity, 10),
        imageUrl,
      };

      const res = await fetch('/api/products', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error('Failed to save product');

      // Reset form
      setProductName('');
      setProductPrice('');
      setProductQuantity('');
      setProductImage(null);
      setErrors({});
      setIsModalOpen(false);
      // Optionally refresh list
    } catch (err) {
      console.error(err);
      alert('Error uploading product: ' + err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle file input change
  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      setProductImage(e.target.files[0]);
    }
  };

  // Filter inventory based on search
  const filteredInventory = allProducts.filter((p) => {
    const query = searchQuery.toLowerCase().trim();
    if (!query) return true;
    return (
      (p.name || "").toLowerCase().includes(query) ||
      (p.productCode || p.id || "").toLowerCase().includes(query) ||
      (p.category || "").toLowerCase().includes(query)
    );
  });

  return (
    <div className={styles["dashboard-layout"]}>
      {/* Sidebar omitted for brevity, unchanged */}
      
      {/* Main Content */}
      <main className={styles["workspace-area"]}>
        {/* ... existing header and metrics ... */}

        {/* Inventory Table */}
        <div className={styles["table-housing"]}>
          <table className={styles["pro-table"]}>
            {/* ... existing table headers ... */}
            <tbody>
              {isLoading ? (
                <tr>
                  <td colSpan="5" className="text-center py-12 text-slate-400 font-medium">
                    Synchronizing database tables...
                  </td>
                </tr>
              ) : filteredInventory.length === 0 ? (
                <tr>
                  <td colSpan="5" className="text-center py-12 text-slate-400 font-medium">
                    No matching inventory files discovered.
                  </td>
                </tr>
              ) : (
                filteredInventory.map((product) => {
                  const displayCode =
                    product.productCode ||
                    product.id?.substring(0, 8).toUpperCase() ||
                    "PENDING";
                  const filename = (product.imageUrl || "").split("/").pop();
                  const finalImageUrl = `${API_URL}/images/${filename}`;

                  return (
                    <tr key={product.id || product._id}>
                      {/* ... product row ... */}
                      <td className="flex items-center gap-3">
                        <img
                          src={finalImageUrl}
                          alt={product.name}
                          className="w-12 h-12 rounded-xl object-cover bg-slate-100 border border-slate-200/60 shadow-xs"
                          onError={(e) => {
                            e.target.src = "https://unsplash.com";
                          }}
                        />
                        <div>
                          <div className="font-bold text-slate-800 text-sm">
                            {product.name || "Untitled Profile"}
                          </div>
                          <div className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">
                            {product.category || "General"}
                          </div>
                        </div>
                      </td>
                      {/* ... other columns ... */}
                      <td className="font-mono text-xs text-emerald-700 font-bold">
                        {product.productCode || "N/A"}
                      </td>
                      {/* ... status, quantity, price ... */}
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </main>

      {/* Add Product Modal */}
      {isModalOpen && (
        <div className={styles["modal-overlay"]}>
          <div className={styles["modal-card"]}>
            <h3 className="text-lg font-bold text-slate-900 mb-1">Add Product Asset Card</h3>
            <p className="text-xs text-slate-400 mb-4">Populate the form below to add a new product.</p>
            {/* Image Upload */}
            <div className="flex items-center gap-4 mb-4 p-3 bg-emerald-50/50 rounded-2xl border border-emerald-100/50">
              <div className="w-16 h-16 rounded-xl bg-white border border-slate-200 flex items-center justify-center overflow-hidden shadow-xs">
                {productImage ? (
                  <img
                    src={URL.createObjectURL(productImage)}
                    alt="Upload Preview"
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <span className="text-xl">🖼️</span>
                )}
              </div>
              <div className="flex-1">
                <label className="block text-[10px] font-bold text-emerald-700 uppercase mb-1">Product Media Graphic</label>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleFileChange}
                  className="block w-full text-xs text-slate-500 file:mr-3 file:py-1 file:px-3 file:rounded-full file:border-0 file:text-[10px] file:font-bold file:bg-emerald-700 file:text-white hover:file:bg-emerald-800 cursor-pointer"
                />
              </div>
            </div>
            {/* Input Fields */}
            <div className="space-y-3 mb-6">
              <input
                type="text"
                placeholder="Product Name"
                value={productName}
                onChange={(e) => setProductName(e.target.value)}
                className={styles["search-input"]}
              />
              {errors.name && <div className="text-red-500 text-xs">{errors.name}</div>}
              <div className="grid grid-cols-2 gap-2">
                <input
                  type="number"
                  placeholder="Price (KES)..."
                  value={productPrice}
                  onChange={(e) => setProductPrice(e.target.value)}
                  className={styles["search-input"]}
                />
                {errors.price && <div className="text-red-500 text-xs">{errors.price}</div>}
                <input
                  type="number"
                  placeholder="Stock density units..."
                  value={productQuantity}
                  onChange={(e) => setProductQuantity(e.target.value)}
                  className={styles["search-input"]}
                />
                {errors.quantity && <div className="text-red-500 text-xs">{errors.quantity}</div>}
              </div>
            </div>
            {/* Buttons */}
            <div className="flex justify-end gap-2">
              <button
                onClick={() => {
                  setIsModalOpen(false);
                  setProductImage(null);
                }}
                className={styles["secondary-btn"]}
              >
                Dismiss
              </button>
              <button
                onClick={handleSubmit}
                className={styles["primary-btn"]}
                disabled={isSubmitting}
              >
                {isSubmitting ? "Uploading..." : "Commit Stream"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
