import { useEffect, useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import useAuth from "../../features/auth/hooks/useAuth";
import styles from "./MyShopDashboard.module.css";

const API_URL = "http://localhost:3000";

export default function MyShopDashboard() {
  const navigate = useNavigate();
  const { auth } = useAuth();
  const currentUserId = auth?.currentUser?.uid;

  // Navigation, Search, and Master Data States
  const [activeTab, setActiveTab] = useState("inventory");
  const [allProducts, setAllProducts] = useState([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [isLoading, setIsLoading] = useState(true);

  // Financial and Aggregated Stats States
  const [walletBalance, setWalletBalance] = useState("0.00");
  const [totalRevenue, setTotalRevenue] = useState(0);
  const [totalSold, setTotalSold] = useState(0);
  const [sidebarOrderCount, setSidebarOrderCount] = useState(0);

  // Modal & File Upload States
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [previewUrl, setPreviewUrl] = useState(null);
  const fileInputRef = useRef(null);

  // ==========================================================================
  // 1. Unified Synchronization Sequence (Triggers on Session Ready)
  // ==========================================================================
  useEffect(() => {
    if (!currentUserId) return;

    const runMasterDashboardSync = async () => {
      try {
        setIsLoading(true);

        // A. Fetch Personal Inventory
        const invResponse = await fetch(
          `${API_URL}/api/products?shopId=${currentUserId}`,
        );
        if (invResponse.ok) {
          const invData = await invResponse.json();
          setAllProducts(invData);
        }

        // B. Fetch Sales Aggregation Stats
        await loadSalesStats();

        // C. Fetch Realtime Wallet Balances (Passing required headers)
        await syncDashboardWalletBalance();
      } catch (err) {
        console.error("Master dashboard sync cycle interrupted:", err);
      } finally {
        setIsLoading(false);
      }
    };

    runMasterDashboardSync();
  }, [currentUserId]);

  // ==========================================================================
  // 2. Fetcher Pipelines
  // ==========================================================================
  const syncDashboardWalletBalance = async () => {
    try {
      const response = await fetch(`${API_URL}/api/wallets/balance`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          "x-user-id": currentUserId, // Middleware verification token header
        },
      });

      if (!response.ok) throw new Error("Could not map balance profile.");
      const data = await response.json();

      if (data.wallet) {
        const formatted = parseFloat(data.wallet.balance || 0).toLocaleString(
          "en-KE",
          {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          },
        );
        setWalletBalance(formatted);
      }
    } catch (err) {
      console.error("Balance asset verification skipped:", err);
    }
  };

  const loadSalesStats = async () => {
    try {
      const response = await fetch(`${API_URL}/api/products/sales-summary`);
      if (response.ok) {
        const data = await response.json();
        setTotalRevenue(data.revenue || 0);
        setTotalSold(data.count || 0);
        setSidebarOrderCount(data.count || 0);
      }
    } catch (err) {
      console.log(
        "Sales analytics matrices not yet generated by backend nodes.",
      );
    }
  };

  // ==========================================================================
  // 3. Export Data Engine (CSV Stream Builder)
  // ==========================================================================
  const handleExportSalesCSV = async () => {
    try {
      const response = await fetch(
        `${API_URL}/api/products/sales-summary-full`,
      );
      const sales = await response.json();

      if (!sales || sales.length === 0) {
        alert("No active transaction data logs found to compile.");
        return;
      }

      const headers = ["Date", "Order ID", "Product", "Code", "Qty", "Total"];
      const rows = sales.map((s) => [
        new Date(s.date).toLocaleDateString("en-KE"),
        s.orderId,
        s.productName,
        s.productCode,
        s.qtySold,
        s.totalPrice,
      ]);

      const csvContent = [headers, ...rows].map((e) => e.join(",")).join("\n");
      const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
      const url = window.URL.createObjectURL(blob);

      const link = document.createElement("a");
      link.setAttribute("href", url);
      link.setAttribute(
        "download",
        `sales_report_${new Date().toLocaleDateString("en-KE")}.csv`,
      );
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) {
      alert("Failed to build and export CSV record stream.");
    }
  };

  // ==========================================================================
  // 4. File Upload Preview Handlers
  // ==========================================================================
  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setPreviewUrl(event.target.result);
      };
      reader.readAsDataURL(file);
    }
  };

  // Filtering implementation handles queries natively
  const filteredInventory = allProducts.filter((p) => {
    const query = searchQuery.toLowerCase().trim();
    if (!query) return true;
    return (
      (p.name || "").toLowerCase().includes(query) ||
      (p.productCode || p.id || "").toLowerCase().includes(query) ||
      (p.category || "").toLowerCase().includes(query)
    );
  });

  return (
    <div className={styles["dashboard-layout"]}>
      {/* SIDEBAR NAVIGATION PANEL */}
      <aside className={styles["sidebar-panel"]}>
        <div className={styles["brand-row"]}>
          <div className={styles["brand-icon-box"]}>
            <svg
              xmlns="http://w3.org"
              width="18"
              height="18"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              viewBox="0 0 24 24"
            >
              <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
            </svg>
          </div>
          <h1 className={styles["brand-title"]}>
            myShop <span className={styles["brand-accent"]}>Pro</span>
          </h1>
        </div>

        <nav className={styles["nav-menu"]}>
          <button
            type="button"
            onClick={() => setActiveTab("inventory")}
            className={`${styles["sidebar-link"]} ${activeTab === "inventory" ? styles["sidebar-link-active"] : ""}`}
          >
            <span>📦 Inventory Portal</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab("sales")}
            className={`${styles["sidebar-link"]} ${activeTab === "sales" ? styles["sidebar-link-active"] : ""}`}
          >
            <span>📊 Sales Reports</span>
            <span className={styles["badge-count"]}>{sidebarOrderCount}</span>
          </button>

          <button
            type="button"
            onClick={() => navigate("/marketplace")}
            className={styles["sidebar-link"]}
          >
            <span>🛒 Browse MarketHub</span>
          </button>

          <button
            type="button"
            onClick={() => navigate("/")}
            className={styles["sidebar-link"]}
          >
            <span>🏠 Home Landing Page</span>
          </button>
        </nav>

        <div className="mt-auto pt-4 border-t border-slate-100">
          <button
            type="button"
            onClick={() => setIsModalOpen(true)}
            className={styles["primary-btn"]}
            style={{
              width: "100%",
              justifyContent: "center",
              display: "flex",
              gap: "0.5rem",
            }}
          >
            <span>+ Record Quick Sale</span>
          </button>
        </div>
      </aside>
      {/* ==========================================================================
         WORKSPACE AREA 
         ========================================================================== */}
      <main className={styles["workspace-area"]}>
        <header className={styles["workspace-header"]}>
          <div>
            <h2 className="text-2xl font-extrabold text-slate-900">
              {auth?.currentUser?.displayName
                ? `${auth.currentUser.displayName}'s Dashboard`
                : "Loading Inventory..."}
            </h2>
            <div className={styles["wallet-capsule"]}>
              <div className={styles["wallet-icon"]}>💳</div>
              <div>
                <span className="text-[10px] text-slate-400 font-extrabold uppercase tracking-wider block">
                  Sokodigi Balance
                </span>
                <span className={styles["wallet-value"]}>
                  KES {walletBalance}
                </span>
              </div>
            </div>
          </div>

          {/* Quick Search */}
          <div className={styles["search-field-box"]}>
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search by product name or code token..."
              className={styles["search-input"]}
            />
          </div>

          <div className={styles["header-btn-row"]}>
            <button
              type="button"
              onClick={handleExportSalesCSV}
              className={styles["secondary-btn"]}
            >
              📥 Export CSV Report
            </button>
            <button
              type="button"
              onClick={() => setIsModalOpen(true)}
              className={styles["primary-btn"]}
            >
              + Add New Inventory
            </button>
          </div>
        </header>

        {/* Aggregated ribbon metrics tiles */}
        <div className={styles["metrics-ribbon"]}>
          <div
            className={styles["metric-card"]}
            style={{ borderLeft: "4px solid #2e7d32" }}
          >
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
              Gross Revenue Aggregate
            </span>
            <h3>KES {totalRevenue.toLocaleString("en-KE")}</h3>
          </div>
          <div
            className={styles["metric-card"]}
            style={{ borderLeft: "4px solid #0284c7" }}
          >
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
              Items Dispatched
            </span>
            <h3>{totalSold} Units Sold</h3>
          </div>
        </div>

        {/* INVENTORY MASTER TABLE */}
        <div className={styles["table-housing"]}>
          <table className={styles["pro-table"]}>
            <thead>
              <tr>
                <th>Product Details</th>
                <th>Product Code</th>
                <th>Status Badge</th>
                <th>Remaining Quantity</th>
                <th>Price Matrix</th>
              </tr>
            </thead>
            <tbody>
              {isLoading ? (
                <tr>
                  <td
                    colSpan="5"
                    className="text-center py-12 text-slate-400 font-medium"
                  >
                    Synchronizing database tables...
                  </td>
                </tr>
              ) : filteredInventory.length === 0 ? (
                <tr>
                  <td
                    colSpan="5"
                    className="text-center py-12 text-slate-400 font-medium"
                  >
                    No matching inventory files discovered.
                  </td>
                </tr>
              ) : (
                filteredInventory.map((product) => {
                  const displayCode =
                    product.productCode ||
                    product.id?.substring(0, 8).toUpperCase() ||
                    "PENDING";
                  const filename = (product.imageUrl || "").split("/").pop();
                  const finalImageUrl = `${API_URL}/images/${filename}`;

                  return (
                    <tr key={product.id || product._id}>
                      <td className="flex items-center gap-3">
                        <img
                          src={finalImageUrl}
                          alt={product.name}
                          className="w-12 h-12 rounded-xl object-cover bg-slate-100 border border-slate-200/60 shadow-xs"
                          onError={(e) => {
                            e.target.src = "https://unsplash.com";
                          }}
                        />
                        <div>
                          <div className="font-bold text-slate-800 text-sm">
                            {product.name || "Untitled Profile"}
                          </div>
                          <div className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">
                            {product.category || "General"}
                          </div>
                        </div>
                      </td>
                      <td className="font-mono text-xs text-emerald-700 font-bold">
                        {displayCode}
                      </td>
                      <td>
                        <span
                          className={`${styles["status-pill"]} ${product.status === "LISTED" ? styles["status-active"] : styles["status-pending"]}`}
                        >
                          {product.status || "READY"}
                        </span>
                      </td>
                      <td
                        className={`font-bold text-sm ${product.quantity < 5 ? "text-red-500" : "text-slate-600"}`}
                      >
                        {product.quantity} units
                      </td>
                      <td className="font-extrabold text-slate-900 text-sm">
                        KES{" "}
                        {parseFloat(product.price || 0).toLocaleString("en-KE")}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </main>

      {/* ==========================================================================
         ADD INVENTORY / RECORD TRANSACTION MODAL CONTAINER 
         ========================================================================== */}
      {isModalOpen && (
        <div className={styles["modal-overlay"]}>
          <div className={styles["modal-card"]}>
            <h3 className="text-lg font-bold text-slate-900 mb-1">
              Add Product Asset Card
            </h3>
            <p className="text-xs text-slate-400 mb-4">
              Populate the secure parameters below to append data vectors into
              the wholesale market databases.
            </p>

            {/* Dynamic File Upload Canvas with Live URL Reader Previews */}
            <div className="flex items-center gap-4 mb-4 p-3 bg-emerald-50/50 rounded-2xl border border-emerald-100/50">
              <div className="w-16 h-16 rounded-xl bg-white border border-slate-200 flex items-center justify-center overflow-hidden shrink-0 shadow-xs">
                {previewUrl ? (
                  <img
                    src={previewUrl}
                    alt="Upload Matrix Preview"
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <span className="text-xl">🖼️</span>
                )}
              </div>
              <div className="flex-1">
                <label className="block text-[10px] font-bold text-emerald-700 uppercase mb-1">
                  Product Media Graphic
                </label>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleFileChange}
                  className="block w-full text-xs text-slate-500 file:mr-3 file:py-1 file:px-3 file:rounded-full file:border-0 file:text-[10px] file:font-bold file:bg-emerald-700 file:text-white hover:file:bg-emerald-800 cursor-pointer"
                />
              </div>
            </div>

            <div className="space-y-3 mb-6">
              <input
                type="text"
                placeholder="Item descriptive profile title name..."
                className={styles["search-input"]}
              />
              <div className="grid grid-cols-2 gap-2">
                <input
                  type="number"
                  placeholder="Price (KES)..."
                  className={styles["search-input"]}
                />
                <input
                  type="number"
                  placeholder="Stock density units..."
                  className={styles["search-input"]}
                />
              </div>
            </div>

            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={() => {
                  setIsModalOpen(false);
                  setPreviewUrl(null);
                }}
                className={styles["secondary-btn"]}
              >
                Dismiss
              </button>
              <button
                type="button"
                onClick={() => {
                  setIsModalOpen(false);
                  setPreviewUrl(null);
                }}
                className={styles["primary-btn"]}
              >
                Commit Stream
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
