
import ROLES from "./roles";
import PERMISSIONS from "./permissions";

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_USERS,

    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.MANAGE_MEMBERS,

    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.CREATE_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.DELETE_PRODUCTS,

    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.MANAGE_ORDERS,

    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_INVENTORY,

    PERMISSIONS.VIEW_WALLET,
    PERMISSIONS.MANAGE_WALLET,

    PERMISSIONS.VIEW_COMMISSIONS,
    PERMISSIONS.MANAGE_COMMISSIONS,

    PERMISSIONS.VIEW_NETWORK,
    PERMISSIONS.MANAGE_NETWORK,

    PERMISSIONS.VIEW_SUBSCRIPTIONS,
    PERMISSIONS.MANAGE_SUBSCRIPTIONS,

    PERMISSIONS.VIEW_VIDEOS,
    PERMISSIONS.MANAGE_VIDEOS,

    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.MANAGE_MESSAGES,

    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.CREATE_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,

    PERMISSIONS.VIEW_ORDERS,

    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_INVENTORY,

    PERMISSIONS.VIEW_WALLET,

    PERMISSIONS.VIEW_COMMISSIONS,

    PERMISSIONS.VIEW_NETWORK,

    PERMISSIONS.VIEW_SUBSCRIPTIONS,

    PERMISSIONS.VIEW_VIDEOS,
    PERMISSIONS.CREATE_VIDEOS,

    PERMISSIONS.VIEW_MESSAGES,
  ],

  [ROLES.USER]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.VIEW_WALLET,
    PERMISSIONS.VIEW_SUBSCRIPTIONS,
    PERMISSIONS.VIEW_VIDEOS,
    PERMISSIONS.VIEW_MESSAGES,
  ],
};

export default ROLE_PERMISSIONS;

